/*
*	Pre-computed ADE parameters for lossy metal (semi-infinite conductor) SIBC.
*
*	The surface impedance Z_s(w) = sqrt(j*w*mu0/sigma) is approximated
*	by a constant conductance G0 plus 2 parallel RL branches:
*
*	  Y_s(w) = G0 + 1/(R1+j*w*L1) + 1/(R2+j*w*L2)
*
*	The RL form is mathematically equivalent to the RC form
*	  Y_s(w) = G0 + G1/(1+j*w*tau1) + G2/(1+j*w*tau2)
*	via R_k = 1/G_k, L_k = tau_k/G_k.
*
*	The RL form is used because it matches the conducting sheet's ADE
*	infrastructure and enables the EC_C stability correction.
*
*	Normalized parameters (universal, independent of sigma, f_max):
*	  Omega = w/w_max,  delta = sqrt(mu0/sigma)
*
*	Physical scaling:
*	  G0_phys = G0_hat / (delta * sqrt(w_max))              [S/square]
*	  Rk_phys = Rk_hat * delta * sqrt(w_max)                [Ohm/square]
*	  Lk_phys = Lk_hat * delta / sqrt(w_max)                [H/square]
*
*	Fit bandwidth: 3:1 (Omega_min = 0.333 to 1.0)
*	Max Z_s error: ~1% over the fit band
*
*	Generated by compute_ade_params.py
*/

#ifndef LOSSY_METAL_PARAMETER_H
#define LOSSY_METAL_PARAMETER_H

// Constant conductance G0 (goes into EC_G)
static const double SIBC_G0_HAT  = 3.381767669916173e-01;

// RL branch 1: 1/(R1 + j*Omega*L1)
static const double SIBC_R1_HAT  = 1.461274827188760e+00;
static const double SIBC_L1_HAT  = 1.533175911967931e+00;

// RL branch 2: 1/(R2 + j*Omega*L2)
static const double SIBC_R2_HAT  = 2.436656787933297e-01;
static const double SIBC_L2_HAT  = 2.717138933990912e+00;

#endif // LOSSY_METAL_PARAMETER_H
